services:
  site:
    build:
      context: .
      dockerfile: site/Dockerfile
    container_name: site
    ports:
      - "11007:11007"
    environment:
      # 时区设置
      - TZ=Asia/Shanghai
      # Spring Profile
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
  cms:
    build:
      context: .
      dockerfile: cms/Dockerfile
    container_name: cms
    ports:
      - "11006:11006"
    environment:
      # 时区设置
      - TZ=Asia/Shanghai
      # Spring Profile
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped


